[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.19"
optimizer = true
optimizer_runs = 1000000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
mainnet = "https://rpc.mevblocker.io/"
goerli = "https://ethereum-goerli.publicnode.com"
gnosischain = "https://rpc.gnosischain.com"
sepolia = "https://ethereum-sepolia.publicnode.com"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
